// DO NOT EDIT THIS FILE
#include <iostream>
#include <iomanip>
#include <cmath>
#include "DiscountCalc.h"
#include <chrono>
#include <thread>
#include "logfile.h"
using namespace std;
using namespace std::this_thread;
using namespace std::chrono;

void test(DiscountCalc, float, float, float);

int main(int argc, char const *argv[]) {
    logf use;
    char userChoice;
    DiscountCalc myCalc;
    int b=5,c=0;

    myCalc.price = 70.0;
    myCalc.dollarsOff = 10;
    myCalc.discountPerc = 20;
    myCalc.additionalPerc = 5;
    myCalc.tax = 8.75;
    use.logOpen();
    // Test a few values
    test(myCalc, 76.13, 48.63, 0.001);
    use.logWrite("Event","Printing out testing results.",__LINE__,__PRETTY_FUNCTION__);
    do {
        myCalc = displayMenu();

        cout << fixed << setprecision(6);
        cout << "--------------------" << endl;
        cout << "Original Price: $" << originalPrice(myCalc) << endl
             << "Discounted Price: $" << discountedPrice(myCalc) << endl;

        cout << "Do you wish to continue? ";
        cin >> userChoice;
    } while(userChoice == 'Y' || userChoice == 'y');
    use.logWrite("Event","Printing out the results for the user.",__LINE__,__PRETTY_FUNCTION__);
    int a = b/c;
    use.logWrite("Warning","Printing out any number divided by 0 will crash the program.",__LINE__,__PRETTY_FUNCTION__);
    use.logFlush();
    cout << a << endl;
    use.logClose();
    use.logRead();


    return 0;
}

void test(DiscountCalc myCalc, float expOriginalPrice, float expDiscountedPrice, float accuracy) {
    if( fabs(originalPrice(myCalc) - expOriginalPrice) > accuracy) {
        cout << "Expected: " << expOriginalPrice << endl
             << "Recieved: " << originalPrice(myCalc) << endl;
    } else if( fabs(discountedPrice(myCalc) - expDiscountedPrice) > accuracy) {
        cout << "Expected: " << expDiscountedPrice << endl
             << "Recieved: " << discountedPrice(myCalc) << endl;
    } else {
        cout << "All tests passed!" << endl;
    }
    use.logWrite("Event","Testing calculator accuracy.",__LINE__,__PRETTY_FUNCTION__);
}
